server {
    listen 80;
    server_name medical.jfarinos.keenetic.pro; # El dominio público
    root /var/www/clinicalResource/public;

    index index.php index.html;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \\.php$ {
        include fastcgi_params;
        fastcgi_pass clinical-app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;

        # Forzamos Symfony a pensar que está en HTTPS (porque el router ya lo maneja)
        #fastcgi_param HTTPS on;
        #fastcgi_param HTTP_X_FORWARDED_PROTO https;
        #fastcgi_param HTTP_X_FORWARDED_HOST $host;
        #fastcgi_param HTTP_X_FORWARDED_PORT 443;
        fastcgi_read_timeout 300; # Aumentar el tiempo de espera a 300 segundos (5 minutos)
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
